name: adengage_task
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  
  # C
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.3
  
  # E
  equatable: ^2.0.5


  # F
  flutter_animate: ^4.2.0+1
  flutter_bloc: ^8.1.3
  flutter_file_dialog: ^3.0.1
  flutter_svg: ^2.0.7

  # H 
  hexcolor: ^3.0.1

  
  # P
  path_provider: ^2.0.15


  # R
  rive: ^0.11.8
  http: ^1.1.0
  dio: ^5.3.1





dev_dependencies:

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/
  - assets/download.riv
  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
